<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Delivery_Service-18c381a7-b370-4dd7-9a1c-1663fbdc9399</UserSecretsId>
    <RootNamespace>Delivery_Service</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.2" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.41" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contracts\EVA-ECS.Chat.Contracts\EVA-ECS.Chat.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Delivery-Service.Tests\**\*.cs" />
  </ItemGroup>
</Project>
